export const PERMISSIONS = {
	MANAGE_USERNAMES: 'MANAGE_USERNAMES',
	MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
	MANAGE_USER_DETAILS: 'MANAGE_USER_DETAILS',
	DELETE_USERS: 'DELETE_USERS',
	DELETE_CHIRPS: 'DELETE_CHIRPS',
} as const;

export const PERMISSIONS_LIST = Object.values(PERMISSIONS);
